executable              = radial_data_generator.sh
arguments               = $(ClusterId)$(ProcId)
output                  = ../log/out/rad_gen.$(ClusterId).$(ProcId).out
error                   = ../log/err/rad_gen.$(ClusterId).$(ProcId).err
log                     = ../log/log/rad_gen.$(ClusterId).log
should_transfer_files   = YES
transfer_input_files    = ./radial_data_generator.py
when_to_transfer_output = ON_EXIT
+JobFlavour = "tomorrow"
request_CPUs = 1
request_GPUs = 1
queue
